/* Setup sex type table */
INSERT INTO SEX (SEX_TYPE) VALUES ('Male');
INSERT INTO SEX (SEX_TYPE) VALUES ('Female');

/* Setup component type table */
INSERT INTO COMPONENT (COMPONENT_TYPE) VALUES ('Run');
INSERT INTO COMPONENT (COMPONENT_TYPE) VALUES ('Walk');
INSERT INTO COMPONENT (COMPONENT_TYPE) VALUES ('Push-up');
INSERT INTO COMPONENT (COMPONENT_TYPE) VALUES ('Sit-up');
INSERT INTO COMPONENT (COMPONENT_TYPE) VALUES ('AC');

/* Setup risk category table */
INSERT INTO RISK (RISK_TYPE) VALUES ('Low');
INSERT INTO RISK (RISK_TYPE) VALUES ('Moderate');
INSERT INTO RISK (RISK_TYPE) VALUES ('High');

/* Setup age table */
INSERT INTO AGE (MIN_AGE, MAX_AGE) VALUES ('0', '30');
INSERT INTO AGE (MIN_AGE, MAX_AGE) VALUES ('30', '39');
INSERT INTO AGE (MIN_AGE, MAX_AGE) VALUES ('40', '49');
INSERT INTO AGE (MIN_AGE, MAX_AGE) VALUES ('50', '59');
INSERT INTO AGE (MIN_AGE, MAX_AGE) VALUES ('60', '99');

/* Setup targets table */
INSERT INTO TARGETS (MIN_VALUE, TARGET_VALUE, COMPONENT_ID, SEX_ID, AGE_ID) VALUES('14:00', '13:14', (SELECT COMPONENT_ID FROM COMPONENT WHERE COMPONENT_TYPE = 'Run'), (SELECT SEX_ID FROM SEX WHERE SEX_TYPE = 'Male'), (SELECT AGE_ID FROM AGE WHERE MAX_AGE = '39'));
INSERT INTO TARGETS (MIN_VALUE, TARGET_VALUE, COMPONENT_ID, SEX_ID, AGE_ID) VALUES('39.0', '37.5', (SELECT COMPONENT_ID FROM COMPONENT WHERE COMPONENT_TYPE = 'AC'), (SELECT SEX_ID FROM SEX WHERE SEX_TYPE = 'Male'), (SELECT AGE_ID FROM AGE WHERE MAX_AGE = '39'));
INSERT INTO TARGETS (MIN_VALUE, TARGET_VALUE, COMPONENT_ID, SEX_ID, AGE_ID) VALUES('27', '36', (SELECT COMPONENT_ID FROM COMPONENT WHERE COMPONENT_TYPE = 'Push-up'), (SELECT SEX_ID FROM SEX WHERE SEX_TYPE = 'Male'), (SELECT AGE_ID FROM AGE WHERE MAX_AGE = '39'));
INSERT INTO TARGETS (MIN_VALUE, TARGET_VALUE, COMPONENT_ID, SEX_ID, AGE_ID) VALUES('39', '42', (SELECT COMPONENT_ID FROM COMPONENT WHERE COMPONENT_TYPE = 'Sit-up'), (SELECT SEX_ID FROM SEX WHERE SEX_TYPE = 'Male'), (SELECT AGE_ID FROM AGE WHERE MAX_AGE = '39'));

/* Cardio Table Male, 30-39 */
INSERT INTO CARDIO (MIN_TIME, MAX_TIME, POINTS, COMPONENT_ID, TARGET_ID, RISK_ID, SEX_ID, AGE_ID) VALUES('00:00', '09:34', '60.0', (SELECT COMPONENT_ID FROM COMPONENT WHERE COMPONENT_TYPE = 'Run'), (SELECT TARGET_ID FROM TARGETS WHERE SEX_ID = (SELECT SEX_ID FROM SEX WHERE SEX_TYPE = 'Male') AND AGE_ID = (SELECT AGE_ID FROM AGE WHERE MAX_AGE = '39') AND COMPONENT_ID = (SELECT COMPONENT_ID FROM COMPONENT WHERE COMPONENT_TYPE = 'Run')), (SELECT RISK_ID FROM RISK WHERE RISK_TYPE = 'Low'), (SELECT SEX_ID FROM SEX WHERE SEX_TYPE = 'Male'), (SELECT AGE_ID FROM AGE WHERE MAX_AGE = '39'));
INSERT INTO CARDIO (MIN_TIME, MAX_TIME, POINTS, COMPONENT_ID, TARGET_ID, RISK_ID, SEX_ID, AGE_ID) VALUES('09:35', '09:58', '59.3', (SELECT COMPONENT_ID FROM COMPONENT WHERE COMPONENT_TYPE = 'Run'), (SELECT TARGET_ID FROM TARGETS WHERE SEX_ID = (SELECT SEX_ID FROM SEX WHERE SEX_TYPE = 'Male') AND AGE_ID = (SELECT AGE_ID FROM AGE WHERE MAX_AGE = '39') AND COMPONENT_ID = (SELECT COMPONENT_ID FROM COMPONENT WHERE COMPONENT_TYPE = 'Run')), (SELECT RISK_ID FROM RISK WHERE RISK_TYPE = 'Low'), (SELECT SEX_ID FROM SEX WHERE SEX_TYPE = 'Male'), (SELECT AGE_ID FROM AGE WHERE MAX_AGE = '39'));
INSERT INTO CARDIO (MIN_TIME, MAX_TIME, POINTS, COMPONENT_ID, TARGET_ID, RISK_ID, SEX_ID, AGE_ID) VALUES('09:59', '10:10', '58.6', (SELECT COMPONENT_ID FROM COMPONENT WHERE COMPONENT_TYPE = 'Run'), (SELECT TARGET_ID FROM TARGETS WHERE SEX_ID = (SELECT SEX_ID FROM SEX WHERE SEX_TYPE = 'Male') AND AGE_ID = (SELECT AGE_ID FROM AGE WHERE MAX_AGE = '39') AND COMPONENT_ID = (SELECT COMPONENT_ID FROM COMPONENT WHERE COMPONENT_TYPE = 'Run')), (SELECT RISK_ID FROM RISK WHERE RISK_TYPE = 'Low'), (SELECT SEX_ID FROM SEX WHERE SEX_TYPE = 'Male'), (SELECT AGE_ID FROM AGE WHERE MAX_AGE = '39'));



