CREATE TABLE SEX(
  SEX_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SEX_TYPE CHAR(16) NOT NULL
);

CREATE TABLE COMPONENT(
  COMPONENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  COMPONENT_TYPE CHAR(64) NOT NULL,
  
);

CREATE TABLE RISK(
  RISK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  RISK_TYPE CHAR(16) NOT NULL
);

CREATE TABLE AGE(
  AGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  MIN_AGE CHAR(16) NOT NULL,
  MAX_AGE CHAR(16) NOT NULL
);

CREATE TABLE TARGETS(
  TARGET_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  MIN_VALUE CHAR(16) NOT NULL,
  TARGET_VALUE CHAR(16) NOT NULL,
  FOREIGN KEY (COMPONENT_ID) REFERENCES COMPONENT(COMPONENT_ID),
  FOREIGN KEY (SEX_ID) REFERENCES SEX(SEX_ID),
  FOREIGN KEY (AGE_ID) REFERENCES AGE(AGE_ID)
);

CREATE TABLE CARDIO(
  CARDIO_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  MIN_TIME CHAR(16) NOT NULL,
  MAX_TIME CHAR(16) NOT NULL,
  POINTS CHAR(16) NOT NULL,
  FOREIGN KEY (SEX_ID) REFERENCES SEX(SEX_ID),
  FOREIGN KEY (RISK_ID) REFERENCES RISK(RISK_ID),
  FOREIGN KEY (AGE_ID) REFERENCES AGE(AGE_ID),
  FOREIGN KEY (TARGET_ID) REFERENCES TARGETS(TARGET_ID)
);

CREATE TABLE BODY_COMP(
  BODY_COMP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  AC_VALUE CHAR(16) NOT NULL,
  POINTS CHAR(16) NOT NULL,
  FOREIGN KEY (SEX_ID) REFERENCES SEX(SEX_ID),
  FOREIGN KEY (RISK_ID) REFERENCES RISK(RISK_ID),
  FOREIGN KEY (AGE_ID) REFERENCES AGE(AGE_ID),
  FOREIGN KEY (TARGET_ID) REFERENCES TARGETS(TARGET_ID),
  FOREIGN KEY (COMPONENT_ID) REFERENCES COMPONENT(COMPONENT_ID)
  );

CREATE TABLE MF(
  MF_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  MF_VALUE CHAR(16) NOT NULL,
  POINTS CHAR(16) NOT NULL,
  FOREIGN KEY (SEX_ID) REFERENCES SEX(SEX_ID),
  FOREIGN KEY (RISK_ID) REFERENCES RISK(RISK_ID),
  FOREIGN KEY (AGE_ID) REFERENCES AGE(AGE_ID),
  FOREIGN KEY (TARGET_ID) REFERENCES TARGETS(TARGET_ID),
  FOREIGN KEY (COMPONENT_ID) REFERENCES COMPONENT(COMPONENT_ID)
);

/*
ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID);
CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);
*/
